# Generated by Django 4.1.3 on 2022-11-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utility", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
