# Generated by Django 4.1.3 on 2022-11-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disaster", models.CharField(max_length=30)),
                ("Comment", models.TextField()),
                ("address", models.CharField(max_length=30)),
                ("lat", models.CharField(max_length=30)),
                ("long", models.CharField(max_length=30)),
                ("comment", models.CharField(blank=True, max_length=90)),
            ],
        ),
    ]
