# Generated by Django 4.1.3 on 2022-11-22 10:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="disaster", name="comment",),
        migrations.AddField(
            model_name="disaster",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
