# Generated by Django 4.1.3 on 2022-11-25 16:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236),
                ),
                ("type", models.CharField(max_length=20)),
                ("local", models.CharField(max_length=20)),
            ],
        ),
    ]
