# Generated by Django 4.1.3 on 2022-11-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0002_local"),
    ]

    operations = [
        migrations.RemoveField(model_name="local", name="local",),
        migrations.RemoveField(model_name="local", name="type",),
    ]
