# Generated by Django 4.1.3 on 2022-11-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0005_remove_local_local_remove_local_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="local",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="local",
            name="type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
