# Generated by Django 4.1.3 on 2022-11-28 13:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0006_local_local_local_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaster",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                default=0, null=True, srid=4326
            ),
        ),
    ]
