# Generated by Django 4.1.3 on 2022-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0007_alter_disaster_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disastertype",
            name="name",
            field=models.SlugField(max_length=30),
        ),
    ]
