# Generated by Django 4.1.3 on 2022-11-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0008_alter_disastertype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaster",
            name="rating",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="disaster",
            name="type",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
