# Generated by Django 4.1.3 on 2022-11-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("disasterapi", "0009_alter_disaster_rating_alter_disaster_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="disaster", name="geom",),
    ]
